
export const USER_REG_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_DATA: "SUCCESS_POST_USER_DATA",
    FAIL_USER_DATA: " FAIL_POST_USER_DATA "
};

export const USER_LOGIN_DATA = {
    REQ_USER_LOGIN_DATA: "REQUEST_DATA",
    SUCCESS_USER_LOGIN_DATA: "SUCCESS_POST_USER_LOGIN",
    FAIL_USER_LOGIN_DATA: " FAIL_POST_USER_LOGIN "
};

export const USER_PUT_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_PUT_DATA: "SUCCESS_PUT_USER_DATA",
    FAIL_USER_PUT_DATA: " FAIL_PUT_USER_DATA "
};

export const USER_ID_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_ID_DATA: "SUCCESS_ID_USER_DATA",
    FAIL_USER_ID_DATA: " FAIL_ID_USER_DATA "
};


export const USER_VIEW_DATA = {
    REQ_USER_VIEW_DATA: "REQUEST_DATA",
    SUCCESS_USER_VIEW_DATA: "SUCCESS_VIEW_USER_DATA",
    FAIL_USER_VIEW_DATA: " FAIL_VIEW_USER_DATA "
};

