
export const USER_REG_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_DATA: "SUCCESS_POST_USER_DATA",
    FAIL_USER_DATA: " FAIL_POST_USER_DATA "
};

export const USER_LOGIN_DATA = {
    REQ_USER_LOGIN_DATA: "REQUEST_DATA",
    SUCCESS_USER_LOGIN_DATA: "SUCCESS_POST_USER_LOGIN",
    FAIL_USER_LOGIN_DATA: " FAIL_POST_USER_LOGIN "
};

export const USER_PUT_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_PUT_DATA: "SUCCESS_PUT_USER_DATA",
    FAIL_USER_PUT_DATA: " FAIL_PUT_USER_DATA "
};

export const USER_ID_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_ID_DATA: "SUCCESS_ID_USER_DATA",
    FAIL_USER_ID_DATA: " FAIL_ID_USER_DATA "
};


export const USER_VIEW_DATA = {
    REQ_USER_VIEW_DATA: "REQUEST_DATA",
    SUCCESS_USER_VIEW_DATA: "SUCCESS_VIEW_USER_DATA",
    FAIL_USER_VIEW_DATA: " FAIL_VIEW_USER_DATA "
};

export const SUPPLIER_GET_DATA = {
    REQ_SUPPLIER_GET_DATA: "REQUEST_SUPPLIER_GET_DATA",
    SUCCESS_SUPPLIER_GET_DATA: "SUCCESS_SUPPLIER_GET_DATA",
    FAIL_SUPPLIER_GET_DATA: " FAIL_SUPPLIER_GET_DATA "
};

export const SUPPLIER_POST_DATA = {
    REQ_SUPPLIER_POST_DATA: "REQUEST_SUPPLIER_POST_DATA",
    SUCCESS_SUPPLIER_POST_DATA: "SUCCESS_SUPPLIER_POST_DATA",
    FAIL_SUPPLIER_POST_DATA: " FAIL_SUPPLIER_POST_DATA "
};


export const SUPPLIER_PUT_DATA = {
    REQ_SUPPLIER_PUT_DATA: "REQUEST_SUPPLIER_PUT_DATA",
    SUCCESS_SUPPLIER_PUT_DATA: "SUCCESS_SUPPLIER_PUT_DATA",
    FAIL_SUPPLIER_PUT_DATA: " FAIL_SUPPLIER_PUT_DATA "
};

export const SUPPLIER_GET_MONTH_DATA = {
    REQ_SUPPLIER_GET_MONTH_DATA: "REQUEST_SUPPLIER_GET_MONTH_DATA",
    SUCCESS_SUPPLIER_GET_MONTH_DATA: "SUCCESS_SUPPLIER_GET_MONTH_DATA",
    FAIL_SUPPLIER_GET_MONTH_DATA: " FAIL_SUPPLIER_GET_MONTH_DATA "
};


export const HEADER_GET_MONTH_DATA = {
    REQ_HEADER_GET_MONTH_DATA: "REQUEST_HEADER_GET_MONTH_DATA",
    SUCCESS_HEADER_GET_MONTH_DATA: "SUCCESS_HEADER_GET_MONTH_DATA",
    FAIL_HEADER_GET_MONTH_DATA: " FAIL_HEADER_GET_MONTH_DATA "
};

export const HEADER_GET_DATA = {
    REQ_HEADER_GET_DATA: "REQUEST_HEADER_GET_DATA",
    SUCCESS_HEADER_GET_DATA: "SUCCESS_HEADER_GET_DATA",
    FAIL_HEADER_GET_DATA: " FAIL_HEADER_GET_DATA "
};

export const HEADER_POST_DATA = {
    REQ_HEADER_POST_DATA: "REQUEST_HEADER_POST_DATA",
    SUCCESS_HEADER_POST_DATA: "SUCCESS_HEADER_POST_DATA",
    FAIL_HEADER_POST_DATA: " FAIL_HEADER_POST_DATA "
};

export const HEADER_PUT_DATA = {
    REQ_HEADER_PUT_DATA: "REQUEST_HEADER_PUT_DATA",
    SUCCESS_HEADER_PUT_DATA: "SUCCESS_HEADER_PUT_DATA",
    FAIL_HEADER_PUT_DATA: " FAIL_HEADER_PUT_DATA "
};

export const EMAIL_POST_DATA = {
    REQ_EMAIL_POST_DATA: "REQUEST_EMAIL_POST_DATA",
    SUCCESS_EMAIL_POST_DATA: "SUCCESS_EMAIL_POST_DATA",
    FAIL_EMAIL_POST_DATA: " FAIL_EMAIL_POST_DATA "
};
