
export const STOCK_POST_DATA = {
    REQ_STOCK_POST_DATA: "REQUEST_STOCK_POST_DATA",
    SUCCESS_STOCK_POST_DATA: "SUCCESS_STOCK_POST_DATA",
    FAIL_STOCK_POST_DATA: " FAIL_STOCK_POST_DATA "
};

export const STOCK_GET_DATA = {
    REQ_STOCK_GET_DATA: "REQUEST_STOCK_GET_DATA",
    SUCCESS_STOCK_GET_DATA: "SUCCESS_STOCK_GET_DATA",
    FAIL_STOCK_GET_DATA: " FAIL_STOCK_GET_DATA "
};

export const STOCK_DELETE_DATA = {
    REQ_STOCK_DATA: "REQUEST_STOCK_GET_DATA",
    SUCCESS_STOCK_DELETE_DATA: "SUCCESS_DELETE_STOCK_DATA",
    FAIL_STOCK_DELETE_DATA: " FAIL_DELETE_STOCK_DATA "
};




export const ORDER_POST_DATA = {
    REQ_ORDER_POST_DATA: "REQUEST_ORDER_POST_DATA",
    SUCCESS_ORDER_POST_DATA: "SUCCESS_ORDER_POST_DATA",
    FAIL_ORDER_POST_DATA: " FAIL_ORDER_POST_DATA "
};

export const ORDER_GET_DATA = {
    REQ_ORDER_GET_DATA: "REQUEST_ORDER_GET_DATA",
    SUCCESS_ORDER_GET_DATA: "SUCCESS_ORDER_GET_DATA",
    FAIL_ORDER_GET_DATA: " FAIL_ORDER_GET_DATA "
};

export const ORDER_DELETE_DATA = {
    REQ_ORDER_DATA: "REQUEST_ORDER_GET_DATA",
    SUCCESS_ORDER_DELETE_DATA: "SUCCESS_DELETE_ORDER_DATA",
    FAIL_ORDER_DELETE_DATA: " FAIL_DELETE_ORDER_DATA "
};



