export const Datatype = {
    REQ_DATA: "REQUEST_DATA",
    SUCCESS_DATA: "SUCCESS_POST_DATA",
    FAIL_DATA: " FAIL_POST_DATA "
};

export const PostsDatatype = {
    REQ_POST_DATA: "REQUEST_DATA",
    SUCCESS_POST_DATA: "SUCCESS_GET_POSTS_DATA",
    FAIL_POST_DATA: " FAIL_GET_POSTS_DATA "
};


export const PostsDeleteDatatype = {
    REQ_POST_DELETE_DATA: "REQUEST_DATA",
    SUCCESS_POST_DELETE_DATA: "SUCCESS_GET_POSTS_DELETE_DATA",
    FAIL_POST_DELETE_DATA: " FAIL_GET_POSTS_DELETE_DATA "
};


export const PostsGetPostId = {
    REQ_POST_ID_DATA: "REQUEST_DATA",
    SUCCESS_POST_ID_DATA: "SUCCESS_GET_POSTS_ID_DATA",
    FAIL_POST_ID_DATA: " FAIL_GET_POSTS_ID_DATA "
};


export const PostsPutData = {
    REQ_POST_PUT_DATA: "REQUEST_DATA",
    SUCCESS_POST_PUT_DATA: "SUCCESS_GET_POSTS_PUT_DATA",
    FAIL_POST_PUT_DATA: " FAIL_GET_POSTS_PUT_DATA "
};