export const Datatype = {
    REQ_DATA: "REQUEST_DATA",
    SUCCESS_DATA: "SUCCESS_POST_DATA",
    FAIL_DATA: " FAIL_POST_DATA "
};

export const PostsDatatype = {
    REQ_POST_DATA: "REQUEST_DATA",
    SUCCESS_POST_DATA: "SUCCESS_GET_POSTS_DATA",
    FAIL_POST_DATA: " FAIL_GET_POSTS_DATA "
};


export const PostsDeleteDatatype = {
    REQ_POST_DELETE_DATA: "REQUEST_DATA",
    SUCCESS_POST_DELETE_DATA: "SUCCESS_GET_POSTS_DELETE_DATA",
    FAIL_POST_DELETE_DATA: " FAIL_GET_POSTS_DELETE_DATA "
};


export const PostsGetPostId = {
    REQ_POST_ID_DATA: "REQUEST_DATA",
    SUCCESS_POST_ID_DATA: "SUCCESS_GET_POSTS_ID_DATA",
    FAIL_POST_ID_DATA: " FAIL_GET_POSTS_ID_DATA "
};


export const PostsPutData = {
    REQ_POST_PUT_DATA: "REQUEST_DATA",
    SUCCESS_POST_PUT_DATA: "SUCCESS_GET_POSTS_PUT_DATA",
    FAIL_POST_PUT_DATA: " FAIL_GET_POSTS_PUT_DATA "
};


export const USER_POST_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_DATA: "SUCCESS_POST_USER_DATA",
    FAIL_USER_DATA: " FAIL_POST_USER_DATA "
};

export const USER_LOGIN_DATA = {
    REQ_USER_LOGIN_DATA: "REQUEST_DATA",
    SUCCESS_USER_LOGIN_DATA: "SUCCESS_POST_USER_LOGIN",
    FAIL_USER_LOGIN_DATA: " FAIL_POST_USER_LOGIN "
};


export const USER_GET_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_GET_DATA: "SUCCESS_GET_USER_DATA",
    FAIL_USER_GET_DATA: " FAIL_GET_USER_DATA "
};

export const USER_DELETE_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_DELETE_DATA: "SUCCESS_DELETE_USER_DATA",
    FAIL_USER_DELETE_DATA: " FAIL_DELETE_USER_DATA "
};

export const USER_PUT_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_PUT_DATA: "SUCCESS_PUT_USER_DATA",
    FAIL_USER_PUT_DATA: " FAIL_PUT_USER_DATA "
};

export const USER_ID_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_ID_DATA: "SUCCESS_ID_USER_DATA",
    FAIL_USER_ID_DATA: " FAIL_ID_USER_DATA "
};


export const USER_VIEW_DATA = {
    REQ_USER_DATA: "REQUEST_DATA",
    SUCCESS_USER_VIEW_DATA: "SUCCESS_VIEW_USER_DATA",
    FAIL_USER_VIEW_DATA: " FAIL_VIEW_USER_DATA "
};