const Permission = {
    VIEW_POST_PERMISSION: "VIEW_POST_PERMISSION",
    EDIT_POST_PERMISSION: "EDIT_POST_PERMISSION",
    CREATE_POST_PERMISSION: "CREATE_POST_PERMISSION",
    DELETE_POST_PERMISSION: "DELETE_POST_PERMISSION",
    VIEW_USER_PERMISSION: "VIEW_USER_PERMISSION",
    EDIT_USER_PERMISSION: "EDIT_USER_PERMISSION",
    CREATE_USER_PERMISSION: "CREATE_USER_PERMISSION",
    DELETE_USER_PERMISSION: "DELETE_USER_PERMISSION",
    VIEW_PROFILE: "VIEW_PROFILE"
}

export default Permission;